services:
  app:
    image: file-manager-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      # - "8080:3000"
      - "9100:3000"
    environment:
      # STORAGE_PATH: /data/files
      # MAX_UPLOAD_SIZE_BYTES: "104857600"
      STORAGE_PATH: ${CONTAINER_STORAGE_PATH:-/data/files}
      MAX_UPLOAD_SIZE_BYTES: "${MAX_UPLOAD_SIZE_BYTES:-104857600}"
    volumes:
      # - file_storage:/data/files
      - ${HOST_STORAGE_PATH}:/data/files

# volumes:
#   file_storage:
