version: '3.8'

# prefix for container name
name: kamu-file-manager

services:
  # Node.js Backend Container
  app_node:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
      # Maven repository data
      - base-maven-cache:/home/vscode/.m2

    # Keep container alive
    command: sleep infinity

    # Connect to the same network as the DB
    networks:
      - backend_network
    env_file: .env.example

  # PostgreSQL Database Container
  db_postgres:
    image: postgres:15
    # container_name: base_postgres_db
    # restart: always
    env_file: .env.example
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - base_postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
      - pgadmin_network

  # pgAdmin Container
  pgadmin_wallet:
    image: dpage/pgadmin4
    # container_name: base_pgadmin
    # restart: always
    env_file: .env.example
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      # Pre-configured server list
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      # Bypass password
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    networks:
      - pgadmin_network
    depends_on:
      - db_postgres
    volumes:
      # Injects config file into the container
      - ./servers.json:/pgadmin4/servers.json:ro
      - base_pgadmin_data:/var/lib/pgadmin

networks:
  backend_network:
  pgadmin_network:


volumes:
  base_postgres_data:
  base_pgadmin_data:
  base-maven-cache:
